{% set name = "pygments" %}
{% set version = "2.13.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Pygments-{{ version }}.tar.gz
  sha256: 56a8508ae95f98e2b9bdf93a6be5ae3f7d8af858b43e02c5a2ff083726be40c1

build:
  number: 0
  noarch: python
  entry_points:
    - pygmentize = pygments.cmdline:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - setuptools

test:
  imports:
    - pygments.styles
    - pygments
    - pygments.lexers
    - pygments.filters
    - pygments.formatters
    - pygments.plugin
  commands:
    - pip check
    - pygmentize -h
  requires:
    - pip


about:
  home: http://pygments.org/
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Pygments is a generic syntax highlighter suitable for use in code hosting, forums, wikis or other applications that need to prettify source code.

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - ocefpaf
    - scopatz
